# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addCustomerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import logic.customer
from stylesheet import *


class AddCustomer(object):
    def __init__(self, data, customer=logic.customer.Customer(None, None, None, None)):
        self.data = data
        self.customer = customer

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(809, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(10, 40, 780, 44))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.name.setFont(font)
        self.name.setStyleSheet(TEXT_BOX_STYLE)
        self.name.setText("")
        self.name.setObjectName("name")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(560, 500, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet(BUTTON_STYLE)
        self.backButton.setObjectName("backButton")
        self.addCustomerButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCustomerButton.setGeometry(QtCore.QRect(320, 500, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addCustomerButton.setFont(font)
        self.addCustomerButton.setStyleSheet(BUTTON_STYLE)
        self.addCustomerButton.setObjectName("addCustomerButton")
        self.address = QtWidgets.QLineEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(10, 120, 780, 44))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.address.setFont(font)
        self.address.setStyleSheet(TEXT_BOX_STYLE)
        self.address.setText("")
        self.address.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.address.setObjectName("address")
        self.ph_num = QtWidgets.QLineEdit(self.centralwidget)
        self.ph_num.setGeometry(QtCore.QRect(10, 200, 780, 44))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.ph_num.setFont(font)
        self.ph_num.setStyleSheet(TEXT_BOX_STYLE)
        self.ph_num.setText("")
        self.ph_num.setObjectName("ph_num")
        self.errorLog = QtWidgets.QLabel(self.centralwidget)
        self.errorLog.setGeometry(QtCore.QRect(0, 302, 811, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.errorLog.setFont(font)
        self.errorLog.setStyleSheet("QLabel{\n"

                                    "color: red\n"
                                    "}")
        self.errorLog.setText("")
        self.errorLog.setScaledContents(True)
        self.errorLog.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLog.setWordWrap(True)
        self.errorLog.setObjectName("errorLog")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.addCustomerButton.clicked.connect(lambda: self.add_product())
        self.backButton.clicked.connect(lambda : self.data.draw(self.data.customerWindow))

        if not self.customer.is_empty():
            self.name.setText(self.customer.name)
            self.address.setText(self.customer.address)
            self.ph_num.setText(self.customer.ph)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Customer" if self.customer.is_empty() else "Edit Customer"))
        self.name.setPlaceholderText(_translate("MainWindow", "Enter the name   -   اسم مشتری"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        btn_name = "Add Customer" if self.customer.is_empty() else "Edit Customer"
        self.addCustomerButton.setText(_translate("MainWindow", btn_name))
        self.address.setPlaceholderText(_translate("MainWindow", "Enter the address   -   آدرس مشتری"))
        self.ph_num.setPlaceholderText(_translate("MainWindow", "Enter the ph#   -   شماره تماس مشتری"))


    def add_product(self):
        name = self.name.text().strip()
        address = self.address.text()
        ph_num = self.ph_num.text()

        if name == "" or ph_num == "":
            print("nothing entered")
            self.errorLog.setText("Invalid Inputs!")
            return

        customer = logic.customer.Customer(self.customer.id, name, address, ph_num)
        if customer == self.customer:
            return
        self.data.db.connect()
        if not self.customer.is_empty():
            if not self.customer.edit(self.data.db, customer):
                self.errorLog.setText("Can not edit this Customer")
        else:
            if not customer.push(self.data.db):
                self.errorLog.setText("Can not push to the db!")
        if not self.data.db.commit():
            self.errorLog.setText("Could not commit the changes. Try again!")
        self.data.db.disconnect()
        self.data.draw(self.data.customerWindow)
