# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddProduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QDoubleValidator

import logic.product


class AddProduct(object):
    def __init__(self, data, add_customer=False):
        self.data = data
        self.add_customer = add_customer

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 337)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.id = QtWidgets.QLineEdit(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(20, 30, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.id.setFont(font)
        self.id.setStyleSheet("QLineEdit {\n"
                              "    background-color: #FFFFFF; /* Set the background color */\n"
                              "    border: 2px solid #555555; /* Set the border style */\n"
                              "    border-radius: 5px; /* Set the border radius */\n"
                              "    padding: 5px; /* Set the padding */\n"
                              "    color: #000000; /* Set the text color */\n"
                              "    font-size: 12px; /* Set the font size */\n"
                              "}")
        self.id.setText("")
        self.id.setObjectName("id")
        self.name_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.name_2.setGeometry(QtCore.QRect(20, 80, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.name_2.setFont(font)
        self.name_2.setStyleSheet("QLineEdit {\n"
                                  "    background-color: #FFFFFF; /* Set the background color */\n"
                                  "    border: 2px solid #555555; /* Set the border style */\n"
                                  "    border-radius: 5px; /* Set the border radius */\n"
                                  "    padding: 5px; /* Set the padding */\n"
                                  "    color: #000000; /* Set the text color */\n"
                                  "    font-size: 12px; /* Set the font size */\n"
                                  "}")
        self.name_2.setText("")
        self.name_2.setObjectName("name_2")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(510, 240, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton {\n"
                                      "    background-color: #4d4d4d;\n"
                                      "    color: #ffffff;\n"
                                      "    padding: 8px 16px;\n"
                                      "    border-radius: 20px;\n"
                                      "    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #595959;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: #3d3d3d;\n"
                                      "}")
        self.backButton.setObjectName("backButton")
        self.backButton.clicked.connect(lambda: self.data.draw(self.data.productsWindow))
        self.addProductButton = QtWidgets.QPushButton(self.centralwidget)
        self.addProductButton.setGeometry(QtCore.QRect(270, 240, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addProductButton.setFont(font)
        self.addProductButton.setStyleSheet("QPushButton {\n"
                                            "    background-color: #4d4d4d;\n"
                                            "    color: #ffffff;\n"
                                            "    padding: 8px 16px;\n"
                                            "    border-radius: 20px;\n"
                                            "    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: #595959;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed {\n"
                                            "    background-color: #3d3d3d;\n"
                                            "}")
        self.addProductButton.setObjectName("addProductButton")
        self.addProductButton.clicked.connect(lambda: self.add_product())
        self.price = QtWidgets.QLineEdit(self.centralwidget)
        self.price.setGeometry(QtCore.QRect(20, 130, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.price.setFont(font)
        self.price.setStyleSheet("QLineEdit {\n"
                                 "    background-color: #FFFFFF; /* Set the background color */\n"
                                 "    border: 2px solid #555555; /* Set the border style */\n"
                                 "    border-radius: 5px; /* Set the border radius */\n"
                                 "    padding: 5px; /* Set the padding */\n"
                                 "    color: #000000; /* Set the text color */\n"
                                 "    font-size: 12px; /* Set the font size */\n"
                                 "}")
        validator = QDoubleValidator()
        validator.setDecimals(2)  # Set the number of decimal places
        self.price.setValidator(validator)
        self.price.setText("")
        self.price.setObjectName("price")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslate_ui(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate

        main_window.setWindowTitle(_translate("MainWindow", "Add Product"))
        self.id.setPlaceholderText(_translate("MainWindow", "Enter Product ID"))
        self.name_2.setPlaceholderText(_translate("MainWindow", "Enter Product Name"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.addProductButton.setText(_translate("MainWindow", "Add Product"))
        self.price.setPlaceholderText(_translate("MainWindow", "Enter Product Price"))

    def add_product(self):

        id = self.id.text().strip()
        name = self.name_2.text().strip()
        price = self.price.text()

        if id == "" or name == "" or price == "":
            print("nothing entered")
            return
        price = float(price)
        product = logic.product.Product(id, name, price)
        self.data.db.connect()

        product.push(self.data.db)
        if not self.data.db.commit():
            return
        self.data.db.disconnect()
        self.data.draw(self.data.productsWindow)
