# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\config.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMessageBox, QPushButton, QMainWindow

from logic import config
import logic.db

PUSH_BTN_LIKE_QLINE = """
            QPushButton {
                border: 1px solid gray;
                background-color: white;
                padding: 5px;
                font: 12px;
            }
            QPushButton:hover {
                background-color: #f0f0f0;
            }
        """

QLINE_EDIT = """
            QLineEdit {
                border: 1px solid gray;
                background-color: white;
                padding: 5px;
                font: 12px;
            }
            QLineEdit:hover {
                background-color: #f0f0f0;
            }
        """

def is_int(s):
    try:
        int(s)
        return True
    except ValueError:
        return False
class Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setObjectName("Application Configuration Menu")
        self.setWindowTitle("Configuration")
        self.setWindowFlags(self.windowFlags() & ~Qt.WindowContextHelpButtonHint )
        self.resize(400, 300)
        self.setAutoFillBackground(False)
        self.setSizeGripEnabled(True)
        buttonBox = QtWidgets.QDialogButtonBox(self)
        buttonBox.setGeometry(QtCore.QRect(230, 250, 156, 23))
        buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        widget = QtWidgets.QWidget(self)
        widget.setGeometry(QtCore.QRect(10, 10, 381, 218))
        widget.setObjectName("widget")
        gridLayout = QtWidgets.QGridLayout(widget)
        gridLayout.setContentsMargins(12, 12, 12, 12)
        gridLayout.setHorizontalSpacing(50)
        gridLayout.setVerticalSpacing(0)
        gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setObjectName("label_2")
        gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(widget)
        self.label_4.setObjectName("label_4")
        gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.db_host = QtWidgets.QLineEdit(widget)
        self.db_host.setObjectName("db_host")
        gridLayout.addWidget(self.db_host, 3, 1, 1, 1)
        self.db_password = QtWidgets.QLineEdit(widget)
        self.db_password.setObjectName("db_password")
        gridLayout.addWidget(self.db_password, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(widget)
        self.label_6.setObjectName("label_6")
        gridLayout.addWidget(self.label_6, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(widget)
        self.label.setObjectName("label")
        gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(widget)
        self.label_5.setObjectName("label_5")
        gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.db_port = QtWidgets.QLineEdit(widget)
        self.db_port.setObjectName("db_port")
        gridLayout.addWidget(self.db_port, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(widget)
        self.label_3.setObjectName("label_3")
        gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.db_user_name = QtWidgets.QLineEdit(widget)
        self.db_user_name.setObjectName("db_user_name")
        gridLayout.addWidget(self.db_user_name, 1, 1, 1, 1)
        self.rec_path = QtWidgets.QPushButton(widget)
        self.rec_path.setStyleSheet(PUSH_BTN_LIKE_QLINE)
        gridLayout.addWidget(self.rec_path, 5, 1, 1, 1)
        self.db_name = QtWidgets.QLineEdit(widget)
        self.db_name.setObjectName("db_name")
        gridLayout.addWidget(self.db_name, 1, 0, 1, 1)

        self.db_name.setStyleSheet(QLINE_EDIT)
        self.db_port.setStyleSheet(QLINE_EDIT)
        self.db_host.setStyleSheet(QLINE_EDIT)
        self.db_user_name.setStyleSheet(QLINE_EDIT)
        self.db_password.setStyleSheet(QLINE_EDIT)
        self.db_password.setEchoMode(QtWidgets.QLineEdit.Password)

        self.rec_path.clicked.connect(self.set_path)
        buttonBox.rejected.connect(lambda : self.close())
        buttonBox.accepted.connect(self.accept)
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        conf = config.read()
        if conf is not None:
            self.db_name.setText(conf.db_name)
            self.db_port.setText(str(conf.db_port))
            self.db_host.setText(conf.db_host)
            self.db_password.setText(conf.db_password)
            self.db_user_name.setText(conf.db_user)
            self.rec_path.setText(conf.receipts_dir)

    def set_path(self)->None:
        fname = QtWidgets.QFileDialog.getExistingDirectory()
        self.rec_path.setText(fname)
    def accept(self) -> None:
        if not is_int(self.db_port.text().strip()):
            QMessageBox.information(self, "Warning!!!", "Please Insert correct Configuration Values, Can not connect "
                                                        "to the Database")
            return

        conf = config.Configuration(self.db_name.text().strip(),
                                    self.db_user_name.text().strip(),
                                    self.db_password.text().strip(),
                                    self.db_host.text().strip(),
                                    self.db_port.text().strip(),
                                    self.rec_path.text().strip())
        conf.write()
        db = logic.db.DB(conf.db_name, conf.db_user, conf.db_password, conf.db_host, conf.db_port)
        if not db.connect():
            QMessageBox.information(self, "Warning!!!", "Please Insert correct Configuration Values, Can not connect "
                                                        "to the Database")
        else:
            QMessageBox.information(self, "Successfully Configured",
                                    "Successfully Configured")
            db.disconnect()
            self.close()
    def retranslateUi(self, Dialog)->None:
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "DB Password"))
        self.label_4.setText(_translate("Dialog", "DB Host"))
        self.label_6.setText(_translate("Dialog", "Receipt Path"))
        self.label.setText(_translate("Dialog", "DB Name"))
        self.label_5.setText(_translate("Dialog", "DB Port"))
        self.label_3.setText(_translate("Dialog", "DB User Name"))



