# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class HomeWindow(object):
    def __init__(self, data):
        self.data = data

    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("SMS Book Keeping System")
        HomeWindow.resize(800, 597)
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(6, 30, 791, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 240, 801, 321))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(170, 0, 170, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sellButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sellButton.setFont(font)
        self.sellButton.setStyleSheet("QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 8px 16px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #595959;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3d3d3d;\n"
"}")
        self.sellButton.setObjectName("sellButton")
        self.verticalLayout_2.addWidget(self.sellButton)
        self.InvoiceButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.InvoiceButton.setFont(font)
        self.InvoiceButton.setStyleSheet("QPushButton {\n"
"    background-color: #4d4d4d;\n"
"    color: #ffffff;\n"
"    padding: 8px 16px;\n"
"    border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #595959;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3d3d3d;\n"
"}")
        self.InvoiceButton.setObjectName("InvoiceButton")
        self.verticalLayout_2.addWidget(self.InvoiceButton)
        HomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMore = QtWidgets.QMenu(self.menubar)
        self.menuMore.setObjectName("menuMore")
        HomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomeWindow)
        self.statusbar.setObjectName("statusbar")
        HomeWindow.setStatusBar(self.statusbar)
        self.actionSell = QtWidgets.QAction(HomeWindow)
        self.actionSell.setObjectName("actionSell")
        self.actionInvoice = QtWidgets.QAction(HomeWindow)
        self.actionInvoice.setObjectName("actionInvoice")
        self.actionReceipt = QtWidgets.QAction(HomeWindow)
        self.actionReceipt.setObjectName("actionReceipt")
        self.actionCustomer = QtWidgets.QAction(HomeWindow)
        self.actionCustomer.setObjectName("actionCustomer")
        self.actionconfig = QtWidgets.QAction(HomeWindow)
        self.actionconfig.setObjectName("actionconfig")
        self.actionAbout = QtWidgets.QAction(HomeWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(HomeWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.actionProduct = QtWidgets.QAction(HomeWindow)
        self.actionProduct.setObjectName("actionProduct")

        self.menuMore.addAction(self.actionSell)
        self.menuMore.addAction(self.actionInvoice)
        self.menuMore.addAction(self.actionReceipt)
        self.menuMore.addAction(self.actionCustomer)
        self.menuMore.addAction(self.actionProduct)
        self.menuMore.addSeparator()
        self.menuMore.addAction(self.actionconfig)
        self.menuMore.addAction(self.actionAbout)
        self.menuMore.addSeparator()
        self.menuMore.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMore.menuAction())

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

        self.actionCustomer.triggered.connect(lambda: self.data.draw(self.data.customerWindow))
        self.actionProduct.triggered.connect(lambda: self.data.draw(self.data.productsWindow))
    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "MainWindow"))
        self.label.setText(_translate("HomeWindow", "SMS Book Keeping System"))
        self.sellButton.setText(_translate("HomeWindow", "Sell - فروش"))
        self.InvoiceButton.setText(_translate("HomeWindow", "Invoice - انوایس"))
        self.menuMore.setTitle(_translate("HomeWindow", "More"))
        self.actionSell.setText(_translate("HomeWindow", "Sell"))
        self.actionInvoice.setText(_translate("HomeWindow", "Invoices"))
        self.actionReceipt.setText(_translate("HomeWindow", "Receipts"))
        self.actionCustomer.setText(_translate("HomeWindow", "Customers"))
        self.actionProduct.setText(_translate("HomeWindow", "Products"))
        self.actionconfig.setText(_translate("HomeWindow", "Config"))
        self.actionAbout.setText(_translate("HomeWindow", "About"))
        self.actionQuit.setText(_translate("HomeWindow", "Quit"))



