# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import copyright
import logic.db
import main
import stylesheet
from receipt_id_search import ReceiptIDSearch
class HomeWindow(object):
    def __init__(self, data):
        self.data = data

    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("SMS Book Keeping System")
        HomeWindow.setFixedSize(800, 597)
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(6, 30, 791, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 240, 801, 321))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(170, 0, 170, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sellButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sellButton.setFont(font)
        self.sellButton.setStyleSheet(stylesheet.BUTTON_STYLE)
        self.sellButton.setObjectName("sellButton")
        self.verticalLayout_2.addWidget(self.sellButton)
        self.receipt_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.receipt_button.setFont(font)
        self.receipt_button.setStyleSheet(stylesheet.BUTTON_STYLE)
        self.receipt_button.setObjectName("InvoiceButton")
        self.verticalLayout_2.addWidget(self.receipt_button)
        HomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMore = QtWidgets.QMenu(self.menubar)
        self.menuMore.setObjectName("menuMore")
        HomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomeWindow)
        self.statusbar.setObjectName("statusbar")
        HomeWindow.setStatusBar(self.statusbar)
        self.actionSell = QtWidgets.QAction(HomeWindow)
        self.actionSell.setObjectName("actionSell")
        self.actionReceipt = QtWidgets.QAction(HomeWindow)
        self.actionReceipt.setObjectName("actionReceipt")
        self.actionconfig = QtWidgets.QAction(HomeWindow)
        self.actionconfig.setObjectName("actionconfig")
        self.actionAbout = QtWidgets.QAction(HomeWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(HomeWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.actionProduct = QtWidgets.QAction(HomeWindow)
        self.actionProduct.setObjectName("actionProduct")

        self.menuMore.addAction(self.actionSell)
        self.menuMore.addAction(self.actionReceipt)
        self.menuMore.addAction(self.actionProduct)
        self.menuMore.addSeparator()
        self.menuMore.addAction(self.actionconfig)
        self.menuMore.addAction(self.actionAbout)
        self.menuMore.addSeparator()
        self.menuMore.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMore.menuAction())

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

        self.actionSell.triggered.connect(lambda: self.data.draw(self.data.customerWindow))
        self.sellButton.clicked.connect(lambda: self.data.draw(self.data.customerWindow))
        self.actionProduct.triggered.connect(lambda: self.data.draw(self.data.productsWindow))

        receipt_id_search = ReceiptIDSearch(self.data)
        self.actionReceipt.triggered.connect(lambda : self.data.draw(receipt_id_search))
        self.receipt_button.clicked.connect(lambda : self.data.draw(receipt_id_search))
        self.actionQuit.triggered.connect(lambda : self.data.exit())
        self.actionconfig.triggered.connect(self.re_configure)
        self.actionAbout.triggered.connect(self.about)

    def about(self):
        window = copyright.LicenseDialog(self.data.window)
        window.show()
        window.exec_()
        window.dialog_shown = True


    def re_configure(self):
        config = main.show_config()
        self.data.db = logic.db.DB(config.db_name, config.db_user, config.db_password, config.db_host, config.db_port)
        self.data.receipts_path = config.receipts_dir
    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "SMS"))
        self.label.setText(_translate("HomeWindow", "SMS Book Keeping System"))
        self.sellButton.setText(_translate("HomeWindow", "Sell - فروش"))
        self.receipt_button.setText(_translate("HomeWindow", "Receipt"))
        self.menuMore.setTitle(_translate("HomeWindow", "More"))
        self.actionSell.setText(_translate("HomeWindow", "Sell"))
        self.actionReceipt.setText(_translate("HomeWindow", "Receipts"))
        self.actionProduct.setText(_translate("HomeWindow", "Products"))
        self.actionconfig.setText(_translate("HomeWindow", "Config"))
        self.actionAbout.setText(_translate("HomeWindow", "About"))
        self.actionQuit.setText(_translate("HomeWindow", "Quit"))



