# -*- coding: utf-8 -*-
import datetime

# Form implementation generated from reading ui file 'GUI\reciptIDSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import stylesheet
import logic.sales as sales
from receipt_show import ReciptShow


class ReceiptIDSearch(object):
    def __init__(self, data):
        self.data = data

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 496)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(560, 400, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet(stylesheet.BUTTON_STYLE)
        self.backButton.setObjectName("backButton")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(320, 400, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet(stylesheet.BUTTON_STYLE)
        self.searchButton.setObjectName("searchButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 340, 471, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.by_receipt_id = QtWidgets.QRadioButton(self.widget)
        self.by_receipt_id.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.by_receipt_id)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.by_customer = QtWidgets.QRadioButton(self.widget)
        self.by_customer.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.by_customer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.by_date = QtWidgets.QRadioButton(self.widget)
        self.by_date.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.by_date)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 40, 791, 237))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.key = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.key.setFont(font)
        self.key.setStyleSheet(stylesheet.TEXT_BOX_STYLE)
        self.key.setText("")
        self.key.setObjectName("name")
        self.gridLayout.addWidget(self.key, 0, 0, 2, 3)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget1)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 3, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.by_receipt_id.setChecked(True)
        self.by_receipt_id_call_back()

        self.by_receipt_id.clicked.connect(self.by_receipt_id_call_back)
        self.by_date.clicked.connect(self.by_date_call_back)
        self.by_customer.clicked.connect(self.by_customer_call_back)
        self.searchButton.clicked.connect(self.search_button_call_back)
        self.backButton.clicked.connect(lambda: self.data.draw(self.data.homeWindow))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.by_receipt_id_call_back()

    def search_button_call_back(self):
        if self.by_receipt_id.isChecked():
            self.receipt_id_call_back()
        elif self.by_customer.isChecked():
            pass
        else:
            self.current_date_call_back()

    def current_date_call_back(self):
        current_date = self.calendarWidget.selectedDate().toPyDate()
        start_date = datetime.datetime(current_date.year, current_date.month, current_date.day, 0, 0, 0)
        end_date = datetime.datetime(current_date.year, current_date.month, current_date.day, 23, 59, 59)
        while not self.data.db.connect():
            self.data.db.connect()
        records = sales.Sales.fetch_by_date(start_date, end_date, self.data.db)
        self.data.db.disconnect()
        show = ReciptShow(self.data, records, self)
        self.data.draw(show)


    def receipt_id_call_back(self):
        while not self.data.db.connect():
            self.data.db.connect()
        records = sales.Sales.fetch(self.key.text(), self.data.db)
        self.data.db.disconnect()

        print(records)

    def by_receipt_id_call_back(self):
        _translate = QtCore.QCoreApplication.translate
        self.calendarWidget.setHidden(True)
        self.key.setHidden(False)
        self.key.setPlaceholderText(_translate("MainWindow", "Enter the receiptID:"))

    def by_date_call_back(self):
        self.calendarWidget.setHidden(False)
        self.key.setHidden(True)

    def by_customer_call_back(self):
        _translate = QtCore.QCoreApplication.translate
        self.calendarWidget.setHidden(True)
        self.key.setHidden(False)
        self.key.setPlaceholderText(_translate("MainWindow", "Enter the customer name: "))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.by_receipt_id.setText(_translate("MainWindow", "BY Recipt ID"))
        self.by_customer.setText(_translate("MainWindow", "By Customer"))
        self.by_date.setText(_translate("MainWindow", "By Date"))
        self.key.setPlaceholderText(_translate("MainWindow", "Enter the name   -   اسم مشتری"))
