# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'receiptWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ReciptWindow(object):
    def setupUi(self, ReciptWindow):
        ReciptWindow.setObjectName("ReciptWindow")
        ReciptWindow.resize(1133, 866)
        self.centralwidget = QtWidgets.QWidget(ReciptWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.customersTable = QtWidgets.QTableView(self.centralwidget)
        self.customersTable.setGeometry(QtCore.QRect(10, 50, 811, 761))
        self.customersTable.setStyleSheet("QTableWidget::item {\n"
                                          "    background-color: #f0f0f0; /* Set the default background color for table items */\n"
                                          "}\n"
                                          "\n"
                                          "QTableWidget::item:nth-child(even) {\n"
                                          "    background-color: #ffffff; /* Set the background color for even rows */\n"
                                          "}\n"
                                          "\n"
                                          "QTableWidget::item:hover {\n"
                                          "    background-color: #c0c0c0; /* Set the background color for hovered items */\n"
                                          "}")
        self.customersTable.setAlternatingRowColors(True)
        self.customersTable.setObjectName("customersTable")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(870, 760, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton {\n"
                                      "    background-color: #4d4d4d;\n"
                                      "    color: #ffffff;\n"
                                      "    padding: 8px 16px;\n"
                                      "    border-radius: 20px;\n"
                                      "    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #595959;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: #3d3d3d;\n"
                                      "}")
        self.backButton.setObjectName("backButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(820, 50, 301, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.product = QtWidgets.QComboBox(self.layoutWidget)
        self.product.setObjectName("product")
        self.verticalLayout_2.addWidget(self.product)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.generateReceipt = QtWidgets.QPushButton(self.centralwidget)
        self.generateReceipt.setGeometry(QtCore.QRect(870, 700, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.generateReceipt.setFont(font)
        self.generateReceipt.setStyleSheet("QPushButton {\n"
                                           "    background-color: #4d4d4d;\n"
                                           "    color: #ffffff;\n"
                                           "    padding: 8px 16px;\n"
                                           "    border-radius: 20px;\n"
                                           "    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: #595959;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed {\n"
                                           "    background-color: #3d3d3d;\n"
                                           "}")
        self.generateReceipt.setObjectName("generateReceipt")
        self.customeLabel = QtWidgets.QLabel(self.centralwidget)
        self.customeLabel.setGeometry(QtCore.QRect(10, 0, 81, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.customeLabel.setFont(font)
        self.customeLabel.setObjectName("customeLabel")
        self.receipt_id = QtWidgets.QLabel(self.centralwidget)
        self.receipt_id.setGeometry(QtCore.QRect(100, 0, 721, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.receipt_id.setFont(font)
        self.receipt_id.setText("")
        self.receipt_id.setObjectName("receipt_id")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(830, 540, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(930, 540, 20, 51))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(830, 565, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(960, 540, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.customerPh = QtWidgets.QLabel(self.centralwidget)
        self.customerPh.setGeometry(QtCore.QRect(960, 565, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.customerPh.setFont(font)
        self.customerPh.setText("")
        self.customerPh.setWordWrap(True)
        self.customerPh.setObjectName("customerPh")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(830, 490, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(930, 465, 20, 51))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.rawTotal = QtWidgets.QLabel(self.centralwidget)
        self.rawTotal.setGeometry(QtCore.QRect(960, 465, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rawTotal.setFont(font)
        self.rawTotal.setText("")
        self.rawTotal.setWordWrap(True)
        self.rawTotal.setObjectName("rawTotal")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(830, 465, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.discountedTotal = QtWidgets.QLabel(self.centralwidget)
        self.discountedTotal.setGeometry(QtCore.QRect(960, 490, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.discountedTotal.setFont(font)
        self.discountedTotal.setText("")
        self.discountedTotal.setWordWrap(True)
        self.discountedTotal.setObjectName("discountedTotal")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(820, 260, 301, 43))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addButton_2.setFont(font)
        self.addButton_2.setStyleSheet("QPushButton {\n"
                                       "    background-color: #4d4d4d;\n"
                                       "    color: #ffffff;\n"
                                       "    padding: 8px 16px;\n"
                                       "    border-radius: 20px;\n"
                                       "    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: #595959;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed {\n"
                                       "    background-color: #3d3d3d;\n"
                                       "}")
        self.addButton_2.setObjectName("addButton_2")
        self.horizontalLayout_3.addWidget(self.addButton_2)
        self.addButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton {\n"
                                     "    background-color: #4d4d4d;\n"
                                     "    color: #ffffff;\n"
                                     "    padding: 8px 16px;\n"
                                     "    border-radius: 20px;\n"
                                     "    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4);\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     "    background-color: #595959;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed {\n"
                                     "    background-color: #3d3d3d;\n"
                                     "}")
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_3.addWidget(self.addButton)
        ReciptWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReciptWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 21))
        self.menubar.setObjectName("menubar")
        ReciptWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReciptWindow)
        self.statusbar.setObjectName("statusbar")
        ReciptWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ReciptWindow)
        QtCore.QMetaObject.connectSlotsByName(ReciptWindow)

    def retranslateUi(self, ReciptWindow):
        _translate = QtCore.QCoreApplication.translate
        ReciptWindow.setWindowTitle(_translate("ReciptWindow", "MainWindow"))
        self.backButton.setText(_translate("ReciptWindow", "Back"))
        self.label_4.setText(_translate("ReciptWindow", "Product:"))
        self.label_2.setText(_translate("ReciptWindow", "Ammount:"))
        self.label_3.setText(_translate("ReciptWindow", "Discount%:"))
        self.generateReceipt.setText(_translate("ReciptWindow", "Generate Receipt"))
        self.customeLabel.setText(_translate("ReciptWindow", "Receipt ID: "))
        self.label.setText(_translate("ReciptWindow", "Customer Name:"))
        self.label_5.setText(_translate("ReciptWindow", "Customer ph#:"))
        self.label_7.setText(_translate("ReciptWindow", "Discounted Total:"))
        self.label_9.setText(_translate("ReciptWindow", "Raw Total:"))
        self.addButton_2.setText(_translate("ReciptWindow", "-"))
        self.addButton.setText(_translate("ReciptWindow", "+"))
